name: Android CI

on:
  push:
    branches: [ "*" ]
  pull_request:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android packages
        shell: bash
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager --install \
            "platform-tools" \
            "platforms;android-34" \
            "build-tools;35.0.0" \
            "cmake;3.22.1" \
            "ndk;26.1.10909125"

      - name: Configure local.properties
        shell: bash
        run: |
          echo "sdk.dir=" > local.properties

      - name: Build Debug APK
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: PixelPilot-apk
          path: |
            app/build/outputs/apk/**/app-*.apk
          if-no-files-found: error